# Generated by Django 4.2.6 on 2023-10-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TiposExatames',
            new_name='TiposExames',
        ),
    ]
